services:
  test:
    command: cargo tarpaulin --all --all-features --workspace --timeout 300 --out xml --skip-clean -- --test-threads=2
    security_opt:
      - seccomp:unconfined
    build:
      context: ./
      dockerfile: Dockerfile
      target: builder
